In [1]:
import os
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
def cbtdm(directory):
    vectorizer = CountVectorizer(input='filename', binary=True)

    X = vectorizer.fit_transform([os.path.join(directory, file) for file in os.listdir(directory) if file.endswith('.txt')])

    words = vectorizer.get_feature_names_out()

    binary_matrix = X.toarray()

    return words, binary_matrix.transpose()

In [3]:
def gtfn(directory):
    files = []
    for filename in os.listdir(directory):
        if filename.endswith('.txt'):
            files.append(filename)
    return files

In [4]:
directory = 'TM'
filenames = gtfn(directory)
print(filenames)

['end.txt', 'Intro.txt', 'lo.txt']

In [5]:
words, binary_matrix = cbtdm(directory)

In [6]:
import pandas as pd
X = pd.DataFrame(binary_matrix, index = words, columns = filenames)

In [7]:
X

                end.txt  Intro.txt  lo.txt
all                   0          0       1
am                    0          1       0
and                   0          0       1
are                   0          0       1
banaras               0          1       0
become                1          0       0
body                  1          0       0
cellular              1          0       0
characterstic         0          0       1
characterstics        0          0       1
computer              0          1       0
conciseness           1          0       0
defining              1          0       0
feature               1          0       0
form                  1          0       0
graduate              0          1       0
grow                  0          0       1
growth                0          0       1
hence                 1          0       0
himanshu              0          1       0
hindu                 0          1       0
in                    0          1       1
increase              0          0       1
individual            0          0       1
is                    1          1       1
life                  1          0       0
likewise              0          0       1
living                1          0       1
mass                  0          0       1
number                0          0       1
of                    1          1       1
orgainisation         1          0       0
organinsm             0          0       1
organisms             1          0       1
post                  0          1       0
property              1          0       0
reproduction          0          0       1
science               0          1       0
singh                 0          1       0
studies               0          1       0
the                   1          0       0
therefore             1          0       0
this                  0          1       0
twin                  0          0       1
university            0          1       0
who                   0          1       0

Query Search

In [8]:
np.array(list(X.loc['the']))

array([1, 0, 0])

In [9]:
def andlogic(x,y):
    global result
    a = np.array(list(X.loc[x].astype(bool)))
    b = np.array(list(X.loc[y].astype(bool)))
    result = a & b
    return result

In [10]:
def orlogic(x,y):
    global result
    a = np.array(list(X.loc[x].astype(bool)))
    b = np.array(list(X.loc[y].astype(bool)))
    result = a | b
    return result

In [11]:
def notlogic(x):
    global result
    a = np.array(list(X.loc[x]))
    return np.logical_not(a)

In [12]:
notlogic('who')

array([ True, False,  True])

In [13]:
query = input("Enter your query: ")
x = query.split()
if x[1] =='AND':
  print(andlogic(x[0],x[2]))
elif x[1] =='OR':
  print(orlogic(x[0],x[2]))
if x[0] =='NOT':
  print(notlogic(x[1]))

Enter your query:  himanshu OR all

[False  True  True]

In [15]:
if result[0] == True:
  print(filenames[0])
if result[1] == True:
  print(filenames[1])
if result[2] == True:
  print(filenames[2])

Intro.txt
lo.txt